#!/bin/sh

# Comprueba si el flag $3 está establecido en 1, lo que indica que es un checkout de una rama y no sol>

if [ $3 -eq 1 ]; then

  # Navegar al directorio raíz del repositorio
  cd "$(git rev-parse --show-toplevel)" || exit

  # Opcionalmente, puedes verificar si realmente necesitas reinstalar

  if [ ! -d node_modules ]; then
    echo "Instalando dependencias..."

    npm install

  fi
fi
